package com.example.mq12.clientrestspring;
// Generated 22/07/2017 12:25:05 PM by Hibernate Tools 4.3.1


import java.util.Date;


/**
 * Partido generated by hbm2java
 */

public class Partido  {


     private Integer id;
     private String local;
     private int goleslocal;
     private String visita;
     private int golesvista;
     private String estadio;
     private Date fecha;
     private String jornada;
     private String torneo;
     private String fechaTemporal;

    public Partido() {
    }

	
    public Partido(int goleslocal, int golesvista) {
        this.goleslocal = goleslocal;
        this.golesvista = golesvista;
    }
    public Partido(String local, int goleslocal, String visita, int golesvista, String estadio, Date fecha, String jornada, String torneo) {
       this.local = local;
       this.goleslocal = goleslocal;
       this.visita = visita;
       this.golesvista = golesvista;
       this.estadio = estadio;
       this.fecha = fecha;
       this.jornada = jornada;
       this.torneo = torneo;
    }
   

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }

    

    public int getGoleslocal() {
        return this.goleslocal;
    }
    
    public void setGoleslocal(int goleslocal) {
        this.goleslocal = goleslocal;
    }

    

    public String getVisita() {
        return this.visita;
    }
    
    public void setVisita(String visita) {
        this.visita = visita;
    }

    

    public int getGolesvista() {
        return this.golesvista;
    }
    
    public void setGolesvista(int golesvista) {
        this.golesvista = golesvista;
    }

    

    public String getEstadio() {
        return this.estadio;
    }
    
    public void setEstadio(String estadio) {
        this.estadio = estadio;
    }


    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    

    public String getJornada() {
        return this.jornada;
    }
    
    public void setJornada(String jornada) {
        this.jornada = jornada;
    }

    

    public String getTorneo() {
        return this.torneo;
    }
    
    public void setTorneo(String torneo) {
        this.torneo = torneo;
    }

    /**
     * @return the fechaTemporal
     */
   
    public String getFechaTemporal() {
        return fechaTemporal;
    }

    /**
     * @param fechaTemporal the fechaTemporal to set
     */
    public void setFechaTemporal(String fechaTemporal) {
        this.fechaTemporal = fechaTemporal;
    }




}


